"""
Markdown report generator for the Autonomous Research & Data Analysis Agent.

Assembles the individual findings, code outputs, and charts from each
research step into a single, well-structured Markdown document.
"""

from __future__ import annotations

import base64
import datetime
import os
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional


@dataclass
class ReportSection:
    """A single named section inside a research report."""

    heading: str
    content: str
    code_snippet: Optional[str] = None
    code_output: Optional[str] = None
    figures: Dict[str, str] = field(default_factory=dict)
    """Mapping of figure filename → base64-encoded PNG (for inline embedding)."""


@dataclass
class ResearchReport:
    """Holds all data needed to render a complete Markdown research report."""

    title: str
    query: str
    sections: List[ReportSection] = field(default_factory=list)
    generated_at: str = field(
        default_factory=lambda: datetime.datetime.now(datetime.timezone.utc).strftime(
            "%Y-%m-%d %H:%M UTC"
        )
    )


class ReportGenerator:
    """
    Renders a :class:`ResearchReport` to Markdown.

    Parameters
    ----------
    embed_figures:
        When ``True`` (default), base64-encode PNG figures and embed them
        directly in the Markdown using an ``<img>`` tag so the document is
        fully self-contained.  When ``False``, figures are saved to disk and
        referenced by file path instead.
    output_dir:
        Directory where saved figures are written when ``embed_figures=False``.
        Defaults to the current working directory.
    """

    def __init__(
        self,
        embed_figures: bool = True,
        output_dir: Optional[str] = None,
    ) -> None:
        self.embed_figures = embed_figures
        self.output_dir = output_dir or os.getcwd()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def render(self, report: ResearchReport) -> str:
        """
        Render the report to a Markdown string.

        Parameters
        ----------
        report:
            The :class:`ResearchReport` to render.

        Returns
        -------
        str
            The fully rendered Markdown document.
        """
        blocks: List[str] = []

        # Title & meta
        blocks.append(f"# {report.title}\n")
        blocks.append(
            f"**Research Query:** {report.query}  \n"
            f"**Generated:** {report.generated_at}\n"
        )
        blocks.append("---\n")

        # Table of Contents
        if len(report.sections) > 1:
            blocks.append("## Table of Contents\n")
            for i, section in enumerate(report.sections, 1):
                anchor = self._to_anchor(section.heading)
                blocks.append(f"{i}. [{section.heading}](#{anchor})")
            blocks.append("\n---\n")

        # Sections
        for section in report.sections:
            blocks.append(f"## {section.heading}\n")
            if section.content:
                blocks.append(section.content + "\n")
            if section.code_snippet:
                blocks.append("**Code:**\n")
                blocks.append(f"```python\n{section.code_snippet.strip()}\n```\n")
            if section.code_output:
                blocks.append("**Output:**\n")
                blocks.append(f"```\n{section.code_output.strip()}\n```\n")
            if section.figures:
                for name, b64 in section.figures.items():
                    blocks.append(self._render_figure(name, b64))

        # Footer
        blocks.append("---\n")
        blocks.append(
            "*Report generated by the Autonomous Research & Data Analysis Agent.*"
        )

        return "\n".join(blocks)

    def save(self, report: ResearchReport, path: str) -> str:
        """
        Render and save the report to a ``.md`` file.

        Parameters
        ----------
        report:
            The report to render.
        path:
            Destination file path.  If the path does not end with ``.md`` the
            extension is appended automatically.

        Returns
        -------
        str
            The absolute path of the saved file.
        """
        if not path.endswith(".md"):
            path = path + ".md"
        abs_path = os.path.abspath(path)
        os.makedirs(os.path.dirname(abs_path) or ".", exist_ok=True)
        with open(abs_path, "w", encoding="utf-8") as fh:
            fh.write(self.render(report))
        return abs_path

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _render_figure(self, name: str, b64_data: str) -> str:
        if self.embed_figures:
            return (
                f"**Figure – {name}**\n\n"
                f'<img src="data:image/png;base64,{b64_data}" '
                f'alt="{name}" style="max-width:100%;">\n'
            )
        # Save to disk and reference by relative path
        out_path = os.path.join(self.output_dir, name)
        with open(out_path, "wb") as fh:
            fh.write(base64.b64decode(b64_data))
        return f"**Figure – {name}**\n\n![{name}]({out_path})\n"

    @staticmethod
    def _to_anchor(heading: str) -> str:
        """Convert a section heading to a GitHub-flavoured Markdown anchor."""
        return (
            heading.lower()
            .replace(" ", "-")
            .replace("(", "")
            .replace(")", "")
            .replace("&", "")
            .replace("/", "")
            .replace(":", "")
        )
